### ISSUE TITLE
vectorization

### ISSUE THREAD

**Issue by erikparr** [bobbens/sketch_simplification#10]
After simplification, how can the output be made into vector graphics? It is mentioned in the paper. Can you suggest a preferred method? Thanks

**Comment by bobbens** [comment]
Read the "notes" section in Readme.md. I am copy and pasting the relevant section:

Post-processing is not performed. You can perform it manually with convert out.png bmp:- | mkbitmap - -t 0.3 -o - | potrace --svg --group -t 15 -o - > out.svg.
