### ISSUE TITLE
training dataset release

### ISSUE THREAD

**Issue by emma-sjwang** [bobbens/sketch_simplification#5]
Hello!

Thanks for sharing your wonderful work.
Could you release your training dataset for others reference?

**Comment by bobbens** [comment]
Due to copyright issues we are unable to release the dataset used. However, we are working on releasing a new dataset that does share the copyright issue.

**Comment by emma-sjwang** [comment]
ok.
Thanks anyway.

**Comment by Yijunmaverick** [comment]
Great work! Look forward to your data. Let us know.

**Comment by sarahradial** [comment]
Since you are unable to release the dataset that was used, I would appreciate it if the demo on the website was back online again.
