### ISSUE TITLE
Why the model can generate different results?

### ISSUE THREAD

**Issue by ghaoziang** [bobbens/sketch_simplification#6]
As I run the code each time, the model can generate different outputs from one same input.
For example, with the input image
![test72](https://user-images.githubusercontent.com/32947455/42724603-e4f27832-87a7-11e8-96cd-bffa806fac0f.png)
I got two different results
![1](https://user-images.githubusercontent.com/32947455/42724617-0e3ef328-87a8-11e8-8aa7-29112d75a0a7.png)
![2](https://user-images.githubusercontent.com/32947455/42724620-16e66b78-87a8-11e8-89e7-fc929a33d7bf.png)

The parameters in the model should be fixed. Thus, the model can only output one result from one input.
Why the model can generate different outputs?

**Comment by json2d** [comment]
@ghaoziang are you sure these two outputs are from the same model? compared to mine, the 1st output looks like its from `model_pencil.t7` and the second output looks like `model_mse.t7`

**Comment by bobbens** [comment]
As per @json2d's comment, you are most likely using different models. The output of a model given an input is deterministic and fixed (there is no randomness).
