### ISSUE TITLE
About post processing

### ISSUE THREAD

**Issue by SeaOfOcean** [bobbens/sketch_simplification#9]
Hi, thanks for your great work. You mentioned the post-processing in the readme,

```
convert out.png bmp:- | mkbitmap - -t 0.3 -o - | potrace --svg --group -t 15 -o - > out.svg
```

but did this command mean? what kind of tools does it depends?

**Comment by bobbens** [comment]
Read the manpages for each tool to learn what the parameters mean (and a bash tutorial if you are not familiar with shell scripting). Dependencies are only potrace and imagemagick.
